import { StyleSheet } from 'react-native';
export const styling = StyleSheet.create({
  veiw: {
    flex: 1,
    flexDirection: 'row',
    width: '100%',
    height: 1000,
    alignItems: 'center',

    backgroundColor: '#DCEBF0',
  },
  container: {
    flex: 3,
    flexDirection: 'column',
    height: 600,
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: 'white',
    marginRight: 10,
    borderRadius: 2,
  },
  logo: {
    justifyContent: 'space-around',
    alignItems: 'center',
    flex: 6,
    height: 600,
    backgroundColor: '#212A40',
    marginLeft: 20,
    marginRight: 10,
    borderRadius: 2,
  },
  image: {
    width: 650,
    height: 450,
    margin: 5,
    padding: 2,
  },
  title: {
    flex: 1,
    width: 430,
    height: 25,
    backgroundColor: 'white',
    margin: 10,
    borderBottomColor: '#DBDED7',
    borderBottomWidth: 0.5,
    fontSize: 15,
    fontFamily: 'Optima',
    fontWeight: 'bold',
    color: '#273D59',
  },
  colors: {
    flex: 7,
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: 430,
    height: 430,
    backgroundColor: '#F3F6FA',
    borderRadius: 3,
    marginTop: 10,
  },
  onClick: {
    flex: 0.7,
    justifyContent: 'center',
    alignItems: 'center',
    width: 430,
    height: 20,
    backgroundColor: '#0178FF',
    marginTop: 5,
    marginBottom: 5,

    borderRadius: 3,
  },
  takePicture: {
    top: '80%',
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    height: '10%',
    width: '23%',
    borderWidth: 5,
    borderColor: 'white',
    borderRadius: 50,
    marginBottom: 20,
    marginTop: '1%',
    backgroundColor: 'rgba(52, 52, 52, 0.1)',
  },
  camera: {
    flex: 9,
    position: 'relative',
    height: '100%',
    width: '100%',
    marginTop: '1%',
    borderRadius: 10,
  },
});
